CREATE DATABASE IF NOT EXISTS hitster_musicos CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hitster_musicos;

CREATE TABLE IF NOT EXISTS games (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    pin         CHAR(4) NOT NULL,
    admin_token VARCHAR(64) NOT NULL,
    status      ENUM('waiting','question','results','finished') DEFAULT 'waiting',
    current_round       INT DEFAULT 0,
    total_rounds        INT DEFAULT 10,
    question_started_at TIMESTAMP NULL,
    question_time       INT DEFAULT 30,
    selected_genre      VARCHAR(100) DEFAULT 'Todos',
    show_links          TINYINT(1) DEFAULT 0,
    embed_youtube       TINYINT(1) DEFAULT 0,
    autoplay            TINYINT(1) DEFAULT 0,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_pin (pin)
);

CREATE TABLE IF NOT EXISTS players (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    game_id      INT NOT NULL,
    name         VARCHAR(50) NOT NULL,
    score        INT DEFAULT 0,
    avatar_color VARCHAR(7) DEFAULT '#FF6B6B',
    last_seen    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    joined_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS songs (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    title        VARCHAR(200) NOT NULL,
    artist       VARCHAR(200) NOT NULL,
    year         INT NOT NULL,
    genre        VARCHAR(100),
    spotify_url  VARCHAR(500) NULL,
    youtube_url  VARCHAR(500) NULL
);

CREATE TABLE IF NOT EXISTS game_songs (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    game_id      INT NOT NULL,
    song_id      INT NOT NULL,
    round_number INT NOT NULL,
    options      JSON NULL,
    FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
    FOREIGN KEY (song_id) REFERENCES songs(id)
);

CREATE TABLE IF NOT EXISTS answers (
    id           INT AUTO_INCREMENT PRIMARY KEY,
    game_id      INT NOT NULL,
    player_id    INT NOT NULL,
    song_id      INT NOT NULL,
    year_guess   INT NOT NULL,
    is_correct   TINYINT(1) DEFAULT 0,
    points_earned INT DEFAULT 0,
    answered_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_answer (game_id, player_id, song_id),
    FOREIGN KEY (game_id)   REFERENCES games(id),
    FOREIGN KEY (player_id) REFERENCES players(id),
    FOREIGN KEY (song_id)   REFERENCES songs(id)
);

-- Canciones de muestra (5 décadas, géneros variados)
INSERT INTO songs (title, artist, year, genre) VALUES
 
-- Rock Internacional
('Stairway to Heaven', 'Led Zeppelin', 1971, 'Rock Internacional'),
('Bohemian Rhapsody', 'Queen', 1975, 'Rock Internacional'),
('Hotel California', 'Eagles', 1977, 'Rock Internacional'),
('Back in Black', 'AC/DC', 1980, 'Rock Internacional'),
('Smells Like Teen Spirit', 'Nirvana', 1991, 'Rock Internacional'),
('Sweet Child O Mine', 'Guns N Roses', 1988, 'Rock Internacional'),
('Enter Sandman', 'Metallica', 1991, 'Rock Internacional'),
('Wonderwall', 'Oasis', 1995, 'Rock Internacional'),
('Seven Nation Army', 'The White Stripes', 2003, 'Rock Internacional'),
('Livin on a Prayer', 'Bon Jovi', 1986, 'Rock Internacional'),
('Don\'t Stop Believin\'', 'Journey', 1981, 'Rock Internacional'),
('Eye of the Tiger', 'Survivor', 1982, 'Rock Internacional'),
('Jump', 'Van Halen', 1984, 'Rock Internacional'),
('Pour Some Sugar on Me', 'Def Leppard', 1987, 'Rock Internacional'),
('Under the Bridge', 'Red Hot Chili Peppers', 1992, 'Rock Internacional'),
('Black Hole Sun', 'Soundgarden', 1994, 'Rock Internacional'),
('With or Without You', 'U2', 1987, 'Rock Internacional'),
('Creep', 'Radiohead', 1992, 'Rock Internacional'),
('Mr. Brightside', 'The Killers', 2003, 'Rock Internacional'),
('Last Resort', 'Papa Roach', 2000, 'Rock Internacional'),
('In the End', 'Linkin Park', 2000, 'Rock Internacional'),
 
-- Pop/Rock Español
('En el Rio', 'Vetusta Morla', 2011, 'Pop/Rock Español'),
('La Bicicleta', 'Carlos Vives & Shakira', 2016, 'Pop/Rock Español'),
('Macarena', 'Los del Rio', 1993, 'Pop/Rock Español'),
('Hijo de la Luna', 'Mecano', 1986, 'Pop/Rock Español'),
('La Chica de Ayer', 'Nino Bravo', 1973, 'Pop/Rock Español'),
('Un Año de Amor', 'Mecano', 1988, 'Pop/Rock Español'),
('Resistire', 'Duo Dinamico', 1988, 'Pop/Rock Español'),
('Corazon Partio', 'Alejandro Sanz', 1997, 'Pop/Rock Español'),
('Vivir', 'Ricky Martin', 1995, 'Pop/Rock Español'),
('Eres', 'Cafe Quijano', 1999, 'Pop/Rock Español'),
('La Tortura', 'Shakira ft. Alejandro Sanz', 2005, 'Pop/Rock Español'),
('Contaminate', 'Pedro Guerra', 1996, 'Pop/Rock Español'),
('A quien le importa', 'Alaska y Dinarama', 1986, 'Pop/Rock Español'),
('El Mar', 'La Oreja de Van Gogh', 2000, 'Pop/Rock Español'),
('Antes de que cuente diez', 'Fito y Fitipaldis', 2009, 'Pop/Rock Español'),
('Me quedo contigo', 'Los Chunguitos', 1981, 'Pop/Rock Español'),
('Libre', 'Nino Bravo', 1972, 'Pop/Rock Español'),
('Quiero', 'Miguel Bose', 1991, 'Pop/Rock Español'),
('Mediterraneo', 'Joan Manuel Serrat', 1971, 'Pop/Rock Español'),
('Veneno en la piel', 'Radio Futura', 1990, 'Pop/Rock Español'),
('No me llames dolores', 'OBK', 1991, 'Pop/Rock Español'),
 
-- 80s
('Sweet Dreams', 'Eurythmics', 1983, '80s'),
('Thriller', 'Michael Jackson', 1982, '80s'),
('Take On Me', 'a-ha', 1985, '80s'),
('Girls Just Want to Have Fun', 'Cyndi Lauper', 1983, '80s'),
('Like a Prayer', 'Madonna', 1989, '80s'),
('Don\'t You Forget About Me', 'Simple Minds', 1985, '80s'),
('Every Breath You Take', 'The Police', 1983, '80s'),
('Wake Me Up Before You Go-Go', 'Wham!', 1984, '80s'),
('Tainted Love', 'Soft Cell', 1981, '80s'),
('Come On Eileen', 'Dexys Midnight Runners', 1982, '80s'),
('West End Girls', 'Pet Shop Boys', 1985, '80s'),
('True', 'Spandau Ballet', 1983, '80s'),
('The Power of Love', 'Frankie Goes to Hollywood', 1984, '80s'),
('Don\'t Stop Me Now', 'Queen', 1979, '80s'),
('Faith', 'George Michael', 1987, '80s'),
('Relax', 'Frankie Goes to Hollywood', 1983, '80s'),
('Push It', 'Salt-N-Pepa', 1987, '80s'),
('Always on My Mind', 'Pet Shop Boys', 1987, '80s'),
('Never Gonna Give You Up', 'Rick Astley', 1987, '80s'),
('Total Eclipse of the Heart', 'Bonnie Tyler', 1983, '80s'),
('Africa', 'Toto', 1982, '80s'),
 
-- New Age
('Watermark', 'Enya', 1988, 'New Age'),
('Oxygene', 'Jean-Michel Jarre', 1976, 'New Age'),
('Tubular Bells', 'Mike Oldfield', 1973, 'New Age'),
('Orinoco Flow', 'Enya', 1988, 'New Age'),
('Chariots of Fire', 'Vangelis', 1981, 'New Age'),
('Adagio for Strings', 'William Orbit', 1999, 'New Age'),
('Return to Innocence', 'Enigma', 1994, 'New Age'),
('Sadeness Part I', 'Enigma', 1990, 'New Age'),
('Silence', 'Delerium ft. Sarah McLachlan', 1997, 'New Age'),
('May It Be', 'Enya', 2001, 'New Age'),
('Only Time', 'Enya', 2000, 'New Age'),
('Porcelain', 'Moby', 1999, 'New Age'),
('Teardrop', 'Massive Attack', 1998, 'New Age'),
('Breathe', 'Telepopmusik', 2001, 'New Age'),
('Cafe del Mar', 'Energy 52', 1993, 'New Age'),
('Saltwater', 'Chicane', 1999, 'New Age'),
('Sweet Lullaby', 'Deep Forest', 1992, 'New Age'),
('Equinoxe', 'Jean-Michel Jarre', 1978, 'New Age'),
('Adiemus', 'Karl Jenkins', 1995, 'New Age'),
('Boadicea', 'Enya', 1987, 'New Age'),
('Song of the Sea', 'Clannad', 1982, 'New Age'),
 
-- Rock en Español
('Lamento Boliviano', 'Los Enanitos Verdes', 1994, 'Rock en Español'),
('La Camisa Negra', 'Juanes', 2004, 'Rock en Español'),
('Donde Jugaran los Ninos', 'Mana', 1992, 'Rock en Español'),
('Clavado en un Bar', 'Mana', 1994, 'Rock en Español'),
('Oye mi Amor', 'Mana', 1992, 'Rock en Español'),
('Te Quiero', 'Hombres G', 1987, 'Rock en Español'),
('Devuelveme a mi Chica', 'Hombres G', 1985, 'Rock en Español'),
('En el Muelle de San Blas', 'Mana', 1994, 'Rock en Español'),
('Me Vale', 'Mana', 1996, 'Rock en Español'),
('Persiana Americana', 'Soda Stereo', 1986, 'Rock en Español'),
('De Musica Ligera', 'Soda Stereo', 1990, 'Rock en Español'),
('Cuando Pase el Temblor', 'Soda Stereo', 1985, 'Rock en Español'),
('Que el Ritmo No Pare', 'El Canto del Loco', 2005, 'Rock en Español'),
('Besame', 'El Canto del Loco', 2003, 'Rock en Español'),
('No Digas Nada', 'La Oreja de Van Gogh', 1998, 'Rock en Español'),
('Quiero Ser', 'La Oreja de Van Gogh', 2003, 'Rock en Español'),
('El Universo Sobre Mi', 'Amaral', 2005, 'Rock en Español'),
('Te Necesito', 'Amaral', 2002, 'Rock en Español'),
('Contigo', 'Jarabe de Palo', 1996, 'Rock en Español'),
('La Flaca', 'Jarabe de Palo', 1996, 'Rock en Español'),
('A las Nueve', 'Dover', 1997, 'Rock en Español'),
 
-- Trap/Rap Internacional
('Stan', 'Eminem', 2000, 'Trap/Rap Internacional'),
('Lose Yourself', 'Eminem', 2002, 'Trap/Rap Internacional'),
('HUMBLE.', 'Kendrick Lamar', 2017, 'Trap/Rap Internacional'),
('Sicko Mode', 'Travis Scott', 2018, 'Trap/Rap Internacional'),
('God\'s Plan', 'Drake', 2018, 'Trap/Rap Internacional'),
('Rockstar', 'Post Malone', 2017, 'Trap/Rap Internacional'),
('Old Town Road', 'Lil Nas X', 2019, 'Trap/Rap Internacional'),
('Lucid Dreams', 'Juice WRLD', 2018, 'Trap/Rap Internacional'),
('Bad Guy', 'Billie Eilish', 2019, 'Trap/Rap Internacional'),
('Hotline Bling', 'Drake', 2015, 'Trap/Rap Internacional'),
('XO Tour Llif3', 'Lil Uzi Vert', 2017, 'Trap/Rap Internacional'),
('Mask Off', 'Future', 2017, 'Trap/Rap Internacional'),
('Without Me', 'Eminem', 2002, 'Trap/Rap Internacional'),
('Mo Bamba', 'Sheck Wes', 2018, 'Trap/Rap Internacional'),
('Sunflower', 'Post Malone', 2018, 'Trap/Rap Internacional'),
('In My Feelings', 'Drake', 2018, 'Trap/Rap Internacional'),
('Congratulations', 'Post Malone', 2016, 'Trap/Rap Internacional'),
('Gucci Gang', 'Lil Pump', 2017, 'Trap/Rap Internacional'),
('DNA.', 'Kendrick Lamar', 2017, 'Trap/Rap Internacional'),
('Savage', 'Megan Thee Stallion', 2020, 'Trap/Rap Internacional'),
('MONTERO', 'Lil Nas X', 2021, 'Trap/Rap Internacional'),
 
-- Trap/Rap en Español
('Krippy Kush', 'Bad Bunny & Farruko', 2017, 'Trap/Rap en Español'),
('Taki Taki', 'DJ Snake ft. Ozuna', 2018, 'Trap/Rap en Español'),
('MIA', 'Bad Bunny ft. Drake', 2018, 'Trap/Rap en Español'),
('Dakiti', 'Bad Bunny & Jhay Cortez', 2020, 'Trap/Rap en Español'),
('Con Calma', 'Daddy Yankee & Snow', 2019, 'Trap/Rap en Español'),
('Hawaii', 'Maluma', 2020, 'Trap/Rap en Español'),
('Antes', 'Anuel AA', 2018, 'Trap/Rap en Español'),
('Safaera', 'Bad Bunny', 2020, 'Trap/Rap en Español'),
('China', 'Anuel AA ft. Bad Bunny', 2019, 'Trap/Rap en Español'),
('Callaita', 'Bad Bunny', 2019, 'Trap/Rap en Español'),
('Ella Quiere Beber', 'Anuel AA', 2018, 'Trap/Rap en Español'),
('Loco Contigo', 'DJ Snake ft. J. Balvin', 2019, 'Trap/Rap en Español'),
('Tusa', 'Karol G & Nicki Minaj', 2019, 'Trap/Rap en Español'),
('Bichota', 'Karol G', 2020, 'Trap/Rap en Español'),
('Mala Mia', 'Maluma', 2018, 'Trap/Rap en Español'),
('Pa Ti', 'Jhay Cortez & J. Balvin', 2020, 'Trap/Rap en Español'),
('Te Bote', 'Nio Garcia', 2018, 'Trap/Rap en Español'),
('Sensacion', 'Rauw Alejandro', 2020, 'Trap/Rap en Español'),
('El Mundo Es Mio', 'Bad Bunny', 2016, 'Trap/Rap en Español'),
('Ojitos Lindos', 'Bad Bunny & Bomba Estereo', 2022, 'Trap/Rap en Español'),
('Gatubela', 'Karol G & Maluma', 2021, 'Trap/Rap en Español'),
 
-- Actualidad 2020-2025
('Levitating', 'Dua Lipa', 2020, 'Actualidad'),
('Blinding Lights', 'The Weeknd', 2020, 'Actualidad'),
('drivers license', 'Olivia Rodrigo', 2021, 'Actualidad'),
('Stay', 'Kid Laroi & Justin Bieber', 2021, 'Actualidad'),
('As It Was', 'Harry Styles', 2022, 'Actualidad'),
('Heat Waves', 'Glass Animals', 2020, 'Actualidad'),
('Anti-Hero', 'Taylor Swift', 2022, 'Actualidad'),
('Unholy', 'Sam Smith & Kim Petras', 2022, 'Actualidad'),
('Flowers', 'Miley Cyrus', 2023, 'Actualidad'),
('Cruel Summer', 'Taylor Swift', 2023, 'Actualidad'),
('Vampire', 'Olivia Rodrigo', 2023, 'Actualidad'),
('Ella Baila Sola', 'Eslabon Armado', 2023, 'Actualidad'),
('Quevedo BZRP Session 52', 'Bizarrap & Quevedo', 2022, 'Actualidad'),
('Shakira BZRP Session 53', 'Bizarrap & Shakira', 2023, 'Actualidad'),
('TQG', 'Karol G & Shakira', 2023, 'Actualidad'),
('Cupid', 'FIFTY FIFTY', 2023, 'Actualidad'),
('Paint The Town Red', 'Doja Cat', 2023, 'Actualidad'),
('Espresso', 'Sabrina Carpenter', 2024, 'Actualidad'),
('Beautiful Things', 'Benson Boone', 2024, 'Actualidad'),
('Lose Control', 'Teddy Swims', 2023, 'Actualidad'),
('Die With A Smile', 'Lady Gaga & Bruno Mars', 2024, 'Actualidad');

